name: iEssentials
version: 1.1.1
main: me.heyimsushii.iessentials.IEssentials
api-version: 1.15

commands:
  help:
    description: Shows a list of commands.
    permission: iessentials.help
  ping:
    description: Returns 'Pong!'.
    permission: iessentials.ping
  gamemode:
    description: Changes your gamemode.
    permission: iessentials.gamemode