name: iEssentials
version: 1.0.0
main: me.heyimsushii.iessentials.IEssentials
api-version: 1.15
author: Ludvik "HeyImSushii" Sørensen
commands:
  help:
    description: Shows a list of commands.
    permission: iessentials.help
  ping:
    description: Returns 'Pong!'.
    permission: iessentials.ping
  gamemode:
    description: Changes your gamemode.
    permission: iessentials.gamemode
    aliases:
      - gm
  whois:
    description: Shows information about a player.
    permission: iessentials.whois
  list:
    description: Shows a list of online players.
    permission: iessentials.list
    aliases:
      - playerlist
  heal:
    description: Heals a player.
    permission: iessentials.heal
  feed:
    description: Feeds a player.
    permission: iessentials.feed
  banlist:
    description: Shows a list of banned players.
    permission: iessentials.banlist
  ban:
    description: Bans a player.
    permission: iessentials.ban
  kick:
    description: Kicks a player.
    permission: iessentials.kick
  unban:
    description: Unbans a player.
    permission: iessentials.unban
    aliases:
      - pardon
  clearchat:
    description: Clears the chat.
    permission: iessentials.clearchat
    aliases:
      - cc
  godmode:
    description: Toggles godmode.
    permission: iessentials.godmode
    aliases:
      - tgm
  fly:
    description: Toggles flight mode.
    permission: iessentials.fly
    aliases:
      - flight
  exp:
    description: Gives a certain amount of EXP points or levels to a player.
    permission: iessentials.exp
    aliases:
      - level
      - levels
      - exp
      - xp